AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name of logs storage for AWS Glue Jobs and Lambda functions"

Resources:
  LogsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_logs_storage"
      Description: "Secret storing the S3 bucket name for logs storage created by AWS Glue Jobs and Lambda functions"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-logs-storage-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Purpose"
          Value: "Logs storage"

Outputs:
  LogsSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name of logs storage"
    Value: !Ref LogsSecret