AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name used by Glue Jobs in the Silver Layer (Transformation)"

Resources:
  SilverSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_silver_transformation"
      Description: "Secret storing the S3 bucket name for data transformation in the Silver Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-silver-transformation-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Silver"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"
        - Key: "Component"
          Value: "Transformation"

Outputs:
  SilverSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for the Silver layer"
    Value: !Ref SilverSecret