# YAML EventBridge

# contacto: sergio.tarrero@student.universidadviu.com

AWSTemplateFormatVersion: '2010-09-09'
Description: "Unificación de reglas EventBridge para ejecución de Step Functions y logging"

Resources:
  # Rule 1: Iniciar StateMachineRunCrawlers cuando RunJobs -> SUCCEEDED
  EventBridgeRuleStateMachine:
    Type: AWS::Events::Rule
    Properties:
      Name: TriggerStateMachineRunCrawlers
      Description: "Triggers StateMachineRunCrawlers when StateMachineRunJobs finishes successfully and logs events to CloudWatch."
      EventPattern:
        source:
          - "aws.states"
        detail-type:
          - "Step Functions Execution Status Change"
        detail:
          stateMachineArn:
            - !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:StateMachineRunJobs"
          status:
            - "SUCCEEDED"
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:StateMachineRunCrawlers"
          Id: "TargetStateMachineRunCrawlers"
          RoleArn: !GetAtt EventBridgeInvokeStepFunctionRole.Arn
        - Arn: !GetAtt LogGroupTriggerStateMachine.Arn
          Id: "CloudWatchLogsTarget"

  LogGroupTriggerStateMachine:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/events/TriggerStateMachineRunCrawlers"

  EventBridgeInvokeStepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EventBridgeInvokeStepFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: InvokeStepFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "states:StartExecution"
                Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:StateMachineRunCrawlers"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !GetAtt LogGroupTriggerStateMachine.Arn

  # Rule 2: Cron - Ejecutar StateMachineRunJobs a diario xx:xx UTC
  ScheduledEventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "DailyTriggerStateMachineRunJobs"
      Description: "Triggers StateMachineRunJobs every day at XX:XX AM Madrid time (XX:XX UTC) and logs to CloudWatch."
      ScheduleExpression: "cron(05 11 * * ? *)"
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:StateMachineRunJobs"
          Id: "StateMachineRunJobsTarget"
          RoleArn: !GetAtt ScheduledEventBridgeRole.Arn
        - Arn: !GetAtt LogGroupDailyRunJobs.Arn
          Id: "CloudWatchLogsTarget"

  LogGroupDailyRunJobs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/events/ScheduledStateMachineRunJobs"

  ScheduledEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ScheduledEventBridgeRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: InvokeStepFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "states:StartExecution"
                Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:StateMachineRunJobs"
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !GetAtt LogGroupDailyRunJobs.Arn

Outputs:

  TriggerStateMachineRuleArn:
    Description: "ARN of the EventBridge rule (Trigger on SUCCEEDED)"
    Value: !GetAtt EventBridgeRuleStateMachine.Arn

  ScheduledRuleArn:
    Description: "ARN of the scheduled EventBridge rule"
    Value: !GetAtt ScheduledEventBridgeRule.Arn

  LogGroupTriggerStateMachineArn:
    Description: "ARN of CloudWatch LogGroup for TriggerStateMachine"
    Value: !GetAtt LogGroupTriggerStateMachine.Arn

  LogGroupDailyRunJobsArn:
    Description: "ARN of CloudWatch LogGroup for Scheduled Daily Run"
    Value: !GetAtt LogGroupDailyRunJobs.Arn