AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name used by Glue Jobs in the Bronze Layer (Ingestion)"

Resources:
  BronzeSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_bronze_ingestion"
      Description: "Secret storing the S3 bucket name for data ingestion in the Bronze Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-bronze-ingest-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Bronze"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"

Outputs:
  BronzeSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name"
    Value: !Ref BronzeSecret