AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name used for resource storage like AWS Glue Jobs, Lambda scripts, JSON, YAML files, etc."

Resources:
  ResourcesBucketSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_resources_storage"
      Description: "Secret storing the S3 bucket name for AWS resource storage"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-resources-storage-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Service"
          Value: "ResourceStorage"
        - Key: "Purpose"
          Value: "GlueLambdaJSONYAMLStorage"

Outputs:
  ResourcesBucketSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for resource storage"
    Value: !Ref ResourcesBucketSecret
