AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name used by Glue Jobs in the Gold Layer (Consumption)"

Resources:
  GoldSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_gold_consumption"
      Description: "Secret storing the S3 bucket name for data consumption in the Gold Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-gold-consumption-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Gold"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"
        - Key: "Component"
          Value: "Consumption"

Outputs:
  GoldSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for the Gold layer"
    Value: !Ref GoldSecret