AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the Weatherstack API key"

Resources:
  WeatherstackAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "weatherstack_api"
      Description: "Secret storing the API key for Weatherstack"
      SecretString: 
        !Sub |
          {
            "weatherstack_api_key": "**********************"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Service"
          Value: "Weatherstack"
        - Key: "Purpose"
          Value: "API Key Storage"

Outputs:
  WeatherstackSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the Weatherstack API key"
    Value: !Ref WeatherstackAPISecret