# YAML Secrets Manager 

# contacto: sergio.tarrero@student.universidadviu.com

AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Secrets Manager Secret for storing the S3 bucket name used by Glue Jobs in the Bronze Layer (Ingestion)"

Resources:
  # Bronze Bucket Secret
  BronzeSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_bronze_ingestion"
      Description: "Secret storing the S3 bucket name for data ingestion in the Bronze Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-bronze-ingest-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Bronze"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"

  # Silver Bucket Secret        
  SilverSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_silver_transformation"
      Description: "Secret storing the S3 bucket name for data transformation in the Silver Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-silver-transformation-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Silver"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"
        - Key: "Component"
          Value: "Transformation"

  # Gold Bucket Secret
  GoldSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_gold_consumption"
      Description: "Secret storing the S3 bucket name for data consumption in the Gold Layer"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-gold-consumption-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Layer"
          Value: "Gold"
        - Key: "Purpose"
          Value: "Glue Job Bucket Storage"
        - Key: "Component"
          Value: "Consumption"
  
  # Weatherstack API Secret
  WeatherstackAPISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "weatherstack_api"
      Description: "Secret storing the API key for Weatherstack"
      SecretString: 
        !Sub |
          {
            "weatherstack_api_key": "***********************"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Service"
          Value: "Weatherstack"
        - Key: "Purpose"
          Value: "API Key Storage"

  # Resources Bucket Secret
  ResourcesBucketSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_resources_storage"
      Description: "Secret storing the S3 bucket name for AWS resource storage"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-resources-storage-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Service"
          Value: "ResourceStorage"
        - Key: "Purpose"
          Value: "GlueLambdaJSONYAMLStorage"

  # Logs Bucket Secret
  LogsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "s3_bucket_logs_storage"
      Description: "Secret storing the S3 bucket name for logs storage created by AWS Glue Jobs and Lambda functions"
      SecretString: 
        !Sub |
          {
            "s3_bucket": "datalake-logs-storage-${AWS::Region}-${AWS::AccountId}"
          }
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Purpose"
          Value: "Logs storage"

Outputs:
  # Bronze Bucket Secret ARN
  BronzeSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name"
    Value: !Ref BronzeSecret
  
  # Silver Bucket Secret ARN
  SilverSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for the Silver layer"
    Value: !Ref SilverSecret

  # Gold Bucket Secret ARN
  GoldSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for the Gold layer"
    Value: !Ref GoldSecret

  # Weatherstack API Secret ARN
  WeatherstackSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the Weatherstack API key"
    Value: !Ref WeatherstackAPISecret

  # Resources Bucket Secret ARN
  ResourcesBucketSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name for resource storage"
    Value: !Ref ResourcesBucketSecret

  # Logs Secret ARN
  LogsSecretArn:
    Description: "ARN of the Secrets Manager Secret storing the S3 bucket name of logs storage"
    Value: !Ref LogsSecret
